# Generated by Django 3.2.13 on 2022-06-30 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametrage', '0003_auto_20220630_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='etudprom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mi_session', models.IntegerField(default=1)),
                ('mention_mi_session', models.CharField(blank=True, max_length=100, null=True)),
                ('pourc_mi_session', models.FloatField(blank=True, null=True)),
                ('one_session', models.IntegerField(default=2)),
                ('mention_one_session', models.CharField(blank=True, max_length=100, null=True)),
                ('pourc_one_session', models.FloatField(blank=True, null=True)),
                ('two_session', models.IntegerField(default=3)),
                ('mention_two_session', models.CharField(blank=True, max_length=100, null=True)),
                ('pourc_two_session', models.FloatField(blank=True, null=True)),
                ('trav', models.FloatField(blank=True, null=True)),
                ('stag', models.FloatField(blank=True, null=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.annee')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.etudiants')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.promotions')),
            ],
            options={
                'unique_together': {('matricule', 'promotion', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ponderaton', models.IntegerField()),
                ('heure', models.IntegerField()),
                ('tp', models.IntegerField(default=0)),
                ('interro', models.IntegerField(default=0)),
                ('etat', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.annee')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.cours')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.promotions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'promotion', 'cours', 'annee')},
            },
        ),
    ]
