# Generated by Django 3.2.13 on 2022-06-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseigne',
            options={'verbose_name': 'Prof. Cours', 'verbose_name_plural': 'Prof. Cours'},
        ),
    ]
