# Generated by Django 3.2.13 on 2022-07-06 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0005_auto_20220703_1603'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cote', '0002_alter_enseigne_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lien', models.CharField(max_length=255)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.annee')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.cours')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.etudiants')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.promotions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
