# Generated by Django 3.2.13 on 2022-07-09 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0005_auto_20220703_1603'),
        ('cote', '0003_exemplaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplaire',
            name='numero',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='sesionn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parametrage.sessions'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='exemplaire',
            unique_together={('matricule', 'promotion', 'cours', 'annee', 'sesionn', 'numero')},
        ),
    ]
