# Generated by Django 3.2.13 on 2022-07-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cote', '0005_cote_tempjournalcote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('cotation', 'Menu Cotation'), ('transmission', 'Sous Menu Transmission - Cotation')),
            },
        ),
        migrations.AlterField(
            model_name='cote',
            name='lien',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
