# Generated by Django 3.2.13 on 2022-07-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cote', '0006_auto_20220716_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cote',
            name='sesionn',
            field=models.CharField(choices=[('1', 'Mi-Session'), ('2', '1ere Sessison'), ('3', '2eme Sessison'), ('4', 'Interro'), ('5', 'Tp')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='sesionn',
            field=models.CharField(choices=[('1', 'Mi-Session'), ('2', '1ere Sessison'), ('3', '2eme Sessison'), ('4', 'Interro'), ('5', 'Tp')], max_length=1),
        ),
    ]
