# Generated by Django 3.2.13 on 2022-07-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cote', '0007_auto_20220717_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cote',
            name='sesionn',
            field=models.CharField(choices=[('1', 'Mi-Session'), ('2', '1ere Session'), ('3', '2eme Session'), ('4', 'Interro'), ('5', 'Tp')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='sesionn',
            field=models.CharField(choices=[('1', 'Mi-Session'), ('2', '1ere Session'), ('3', '2eme Session'), ('4', 'Interro'), ('5', 'Tp')], max_length=1),
        ),
        migrations.CreateModel(
            name='delibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opde', models.CharField(max_length=5)),
                ('de', models.FloatField()),
                ('opa', models.CharField(max_length=5)),
                ('a', models.FloatField()),
                ('etat', models.CharField(max_length=10)),
                ('op', models.CharField(max_length=5)),
                ('nbr', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Règle Déliberation',
                'verbose_name_plural': 'Règle Déliberation',
                'unique_together': {('opde', 'de', 'opa', 'a', 'etat', 'op', 'nbr', 'position')},
            },
        ),
    ]
