# Generated by Django 3.2.13 on 2022-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cote', '0008_auto_20220717_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cote',
            name='sesionn',
            field=models.CharField(choices=[('1', 'Mi-Session'), ('2', '1ere Session'), ('3', '2eme Session'), ('5', 'Interro'), ('4', 'Tp')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='sesionn',
            field=models.CharField(choices=[('1', 'Mi-Session'), ('2', '1ere Session'), ('3', '2eme Session'), ('5', 'Interro'), ('4', 'Tp')], max_length=1),
        ),
    ]
