# Generated by Django 3.2.13 on 2022-07-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0007_auto_20220724_1159'),
        ('cote', '0009_auto_20220724_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droit',
            options={'permissions': (('cotation', 'Menu Cotation'), ('transmission', 'Sous Menu Transmission - Cotation'), ('deliberation', 'Sous Menu Deliberation - Cotation'))},
        ),
        migrations.AddField(
            model_name='enseigne',
            name='categorie',
            field=models.IntegerField(choices=[(1, 'Matières de formation professionnelle'), (2, "Matières d'appui formation professionnelle"), (3, 'Matières de formation générale')], default=1),
        ),
        migrations.AlterField(
            model_name='cote',
            name='sesionn',
            field=models.CharField(choices=[('1', 'Mi-Session'), ('2', '1ere Session'), ('3', '2eme Session'), ('5', 'Interro'), ('4', 'Tp'), ('6', 'Session Special')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='sesionn',
            field=models.CharField(choices=[('1', 'Mi-Session'), ('2', '1ere Session'), ('3', '2eme Session'), ('5', 'Interro'), ('4', 'Tp'), ('6', 'Session Special')], max_length=1),
        ),
        migrations.CreateModel(
            name='delibedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dateop', models.DateField()),
                ('president', models.CharField(max_length=255)),
                ('secretaire1', models.CharField(max_length=255)),
                ('secretaire2', models.CharField(max_length=255)),
                ('membres', models.CharField(max_length=255)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.annee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
