# Generated by Django 3.2.8 on 2022-08-04 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametrage', '0008_auto_20220731_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_candidat', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('F', 'Feminin'), ('M', 'Masculin')], default='M', max_length=1, null=True)),
                ('etat_civil', models.CharField(blank=True, choices=[('C', 'Célibataire'), ('M', 'Marié')], default='C', max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, max_length=155, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('etat', models.BooleanField(default=True)),
                ('anne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrage.annee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inscription.candidat')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrage.promotions')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.ImageField(blank=True, default=None, upload_to='img_candidat/')),
                ('candidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inscription.candidat')),
            ],
        ),
    ]
