# Generated by Django 3.2.8 on 2022-08-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0009_promotions_type'),
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testadmin',
            name='candidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatest', to='inscription.candidat'),
        ),
        migrations.AlterField(
            model_name='testadmin',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codpromo', to='parametrage.promotions'),
        ),
    ]
