# Generated by Django 3.2.8 on 2022-08-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0009_promotions_type'),
        ('inscription', '0002_auto_20220808_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='anne',
        ),
        migrations.AddField(
            model_name='testadmin',
            name='anne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrage.annee'),
        ),
    ]
