# Generated by Django 3.2.8 on 2022-08-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_auto_20220808_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='dossier',
            new_name='dossierss',
        ),
    ]
