# Generated by Django 3.2.8 on 2022-08-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_rename_dossier_dossier_dossierss'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='reussie',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
    ]
