# Generated by Django 3.2.8 on 2022-08-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0009_promotions_type'),
        ('inscription', '0005_candidat_reussie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=60, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('etat', models.BooleanField(default=False)),
                ('devise', models.CharField(blank=True, max_length=5, null=True)),
                ('anne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrage.annee')),
            ],
        ),
        migrations.CreateModel(
            name='Paimentinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_candi', models.CharField(blank=True, max_length=25, null=True)),
                ('observation', models.CharField(blank=True, max_length=60, null=True)),
                ('prix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inscription.fixation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
