# Generated by Django 3.2.8 on 2022-08-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0008_auto_20220811_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='paimentinscription',
            name='indice',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
    ]
