# Generated by Django 3.2.8 on 2022-08-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrage', '0009_promotions_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fraisclasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devise', models.CharField(blank=True, max_length=5, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('anne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrage.annee')),
                ('frais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fraiscl', to='paiement.frais')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codpromos', to='parametrage.promotions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
