# Generated by Django 3.2.8 on 2022-08-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraistranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tranche', models.CharField(blank=True, max_length=10, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('devise', models.CharField(blank=True, max_length=5, null=True)),
                ('fraistranche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paiement.fraisclasse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
