# Generated by Django 3.2.8 on 2022-08-24 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametrage', '0009_promotions_type'),
        ('paiement', '0003_alter_fraistranche_tranche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement_frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_paie', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('montantpaie', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('anne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrage.annee')),
                ('matricule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paie_etudiant', to='parametrage.etudiants')),
                ('tranche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paie_tranche', to='paiement.fraistranche')),
                ('type_frais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paie_frais', to='paiement.frais')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
