# Generated by Django 3.2.8 on 2022-08-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0004_paiement_frais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement_frais',
            name='type_frais',
        ),
    ]
