# Generated by Django 3.2.8 on 2022-08-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0005_remove_paiement_frais_type_frais'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_frais',
            name='frais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paiement.frais'),
        ),
    ]
