# Generated by Django 3.2.8 on 2022-09-22 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametrage', '0009_promotions_type'),
        ('paiement', '0006_paiement_frais_frais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression_paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOp', models.DateField(blank=True, null=True)),
                ('code_paie', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('montlettre', models.CharField(blank=True, max_length=255, null=True)),
                ('totalfrais', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('totaltranche', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('montantpaie', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('anne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrage.annee')),
                ('frais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paiement.frais')),
                ('matricule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paie_etudiants', to='parametrage.etudiants')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='parametrage.promotions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
