# Generated by Django 3.2.8 on 2022-09-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0008_impression_paie_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression_paie',
            name='totalpaye',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='impression_paie',
            name='totalreste',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
