# Generated by Django 3.2.8 on 2022-09-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0009_auto_20220922_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression_paie',
            name='tranche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paie_tranches', to='paiement.fraistranche'),
        ),
    ]
