# Generated by Django 3.2.13 on 2022-06-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0002_auto_20220630_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='etudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=1)),
                ('etat_civil', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié')], max_length=20)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(blank=True, max_length=155, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('etat', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='annee',
            options={'verbose_name': 'Annee', 'verbose_name_plural': 'Annees'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='departements',
            options={'verbose_name': 'Departement', 'verbose_name_plural': 'Departements'},
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='promotions',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='universite',
            options={'verbose_name': 'Univesité', 'verbose_name_plural': 'Univesités'},
        ),
    ]
