# Generated by Django 3.2.13 on 2022-07-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cote', '0007_auto_20220717_0854'),
        ('parametrage', '0005_auto_20220703_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sessions',
        ),
    ]
