# Generated by Django 3.2.13 on 2022-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0006_delete_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='libelle',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='sigle',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
