# Generated by Django 3.2.8 on 2022-08-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0008_auto_20220731_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
