# Generated by Django 3.2.8 on 2022-11-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0009_promotions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='universite',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images'),
        ),
    ]
