# Generated by Django 3.2.8 on 2022-11-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0010_universite_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='universite',
            name='ministere',
            field=models.CharField(default="Ministere de l'Enseignement Superieur et Universitaire", max_length=255),
        ),
    ]
